<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260217140145 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE code (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, word1_id_id INT NOT NULL, word2_id_id INT NOT NULL, word3_id_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_771530985C2C91FD ON code (word1_id_id)');
        $this->addSql('CREATE INDEX IDX_771530986DC48B60 ON code (word2_id_id)');
        $this->addSql('CREATE INDEX IDX_77153098CBB380D4 ON code (word3_id_id)');
        $this->addSql('CREATE TABLE word (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, text VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE code ADD CONSTRAINT FK_771530985C2C91FD FOREIGN KEY (word1_id_id) REFERENCES word (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE code ADD CONSTRAINT FK_771530986DC48B60 FOREIGN KEY (word2_id_id) REFERENCES word (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE code ADD CONSTRAINT FK_77153098CBB380D4 FOREIGN KEY (word3_id_id) REFERENCES word (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE code DROP CONSTRAINT FK_771530985C2C91FD');
        $this->addSql('ALTER TABLE code DROP CONSTRAINT FK_771530986DC48B60');
        $this->addSql('ALTER TABLE code DROP CONSTRAINT FK_77153098CBB380D4');
        $this->addSql('DROP TABLE code');
        $this->addSql('DROP TABLE word');
    }
}
